### PR TITLE
Implement conflict solving for axis labels

### PR DESCRIPTION
**Pull request by ivnsch**
Now it's possible to pass a label conflict solver to axis model which implements `ChartAxisLabelsConflictSolver` protocol. It maps the axis labels array to a new/mutated array which allows a wide range of possibilities like changing screen location, filtering out values, changing font size etc. Implemented a first conflict solver for the y axis `ChartAxisLabelsConflictSolverMoveUpDown` which moves the labels up and down by half of frame size with a max iteration limit.

Usage example:

``` swift
let yValues = [0, 2, 2.1, 2.2, 2.3, 4, 6, 8, 10, 12, 14].map {ChartAxisValueDouble($0, labelSettings: labelSettings)}        
let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical()), labelsConflictSolver: ChartAxisLabelsConflictSolverMoveUpDown())
```

### CODE REVIEW

**Comment by iainbryson** [comment]
Curious: why is the main example move up/down?  Isn't a typical example more likely to be similar or identically-sized labels, in which case this won't work?  Our default conflict resolution for this is to remove labels.  Though it would be better to be a little more sophisticated and remove labels evenly (i.e. every 2, then every 3, etc..) until there are no more conflicts.

**Comment by i-schuetz** [comment]
Because a part of the algorithm to move them was [already there](https://github.com/grafiti-io/SwiftCharts/pull/4/commits/c348c734b174e538a379ab4c08daea03f963208a#diff-64e54347721bcd607cecb30167442c88L75). So I had to move it to this more generic functionality (and complete it).

**Comment by ivnsch** [comment]
Because a part of the algorithm to move them was [already there](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Axis/ChartAxisYLayerDefault.swift#L84). So I had to move it to this more generic functionality (and complete it).

**Comment by iainbryson** [comment]
Fair enough.  But I'm curious: what sorts of charts does this work for?

**Comment by ivnsch** [comment]
Charts with axes with irregular intervals. For example you may want to show sometimes labels for the points you're currently showing, instead of regular intervals. There was also recently a project which used the y axis to show depth values of snow layers, where each layer (basically an y range) had a constant x value. So the start/end of these layers depended on the different x values and was not regular.

Of course it assumes a small data set / low probability of conflicts (this was the case e.g in the snow layer use case), which is also why the conflict solver has a max number of passes. So it's rather a special use case.

**Comment by ivnsch** [comment]
p.s. I can add a conflict solver to remove labels.

**Comment by iainbryson** [comment]
Let's add it to the low-priority backlog. It seems straightforward to implement given the infrastructure you've created.  My line of questioning was to make sure my understanding of the context was correct..

**Pull request merged**
